# Generated by Django 5.0 on 2024-01-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
    ]
