# Generated by Django 5.0 on 2024-01-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_comment_comment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aname',
            new_name='arname',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='uname',
            new_name='urname',
        ),
    ]
